import type { ReactNode } from 'react'; import { useRouter } from 'expo-router'; import { Alert, Platform, Pressable, ScrollView, Share, StyleSheet, Switch, Text, View } from 'react-native'; import { SafeAreaView } from 'react-native-safe-area-context';
import { Icon, type IconName } from '@/components/icon'; import { StatTiles } from '@/components/list-kit'; import { SettingRow } from '@/components/setting-row'; import { useAuth } from '@/providers/auth-provider'; import { useCases } from '@/providers/cases-provider'; import { useClients } from '@/providers/clients-provider'; import { useSettings, type AppSettings } from '@/providers/settings-provider'; import { useAppTheme, type ThemePreference } from '@/providers/theme-provider'; import { radius, type ThemeColors } from '@/theme'; import { hashTheme } from '@/utils/palette';
const PLAN_LABELS:Record<string,string>={local:'Plano Local',pro:'Plano Pro',office:'Plano Escritório'};
const THEMES:{id:ThemePreference;label:string;icon:IconName}[]=[{id:'system',label:'Automático',icon:'theme-light-dark'},{id:'light',label:'Claro',icon:'white-balance-sunny'},{id:'dark',label:'Escuro',icon:'weather-night'}];
export default function ProfileScreen(){const router=useRouter();const {logout,user}=useAuth();const {cases}=useCases();const {clients}=useClients();const {settings,updateSettings}=useSettings();const {colors,preference,setPreference}=useAppTheme();const styles=makeStyles(colors);const documents=cases.reduce((sum,item)=>sum+item.documents.length,0);const tasks=cases.reduce((sum,item)=>sum+item.tasks.length,0);const avatarTheme=hashTheme(colors,settings.displayName||'utilizador');const initials=settings.displayName.trim().split(/\s+/).slice(0,2).map((word)=>word[0]).join('').toUpperCase()||'U';const plan=PLAN_LABELS[user?.plan??'local']??'Plano Local';const exportData=async()=>{const payload=JSON.stringify({exportedAt:new Date().toISOString(),clients,cases},null,2);await Share.share({title:'Exportação de dados Lexora',message:payload});};const signOut=async()=>{await logout().catch(()=>undefined);if(Platform.OS==='web'){window.location.href='/login';return;}router.replace('/login');};
const toggle=(symbol:IconName,title:string,description:string,setting:keyof AppSettings,onChange:(patch:Partial<AppSettings>)=>void=updateSettings)=><SettingRow symbol={symbol} title={title} description={description} trailing={<Switch accessibilityLabel={title} value={settings[setting] as boolean} onValueChange={(next)=>onChange({[setting]:next})} trackColor={{false:colors.borderStrong,true:colors.primary}} thumbColor={colors.white}/>}/>;
return <SafeAreaView edges={['top']} style={styles.screen}><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
<View style={styles.pageIntro}><Text style={styles.eyebrow}>CONTA E PREFERÊNCIAS</Text><Text style={styles.pageTitle}>Definições</Text><Text style={styles.pageSubtitle}>Conta, preferências, privacidade e dados da Lexora.</Text></View>
<View style={styles.profileCard}><View style={[styles.avatar,{backgroundColor:avatarTheme.bg}]}><Text style={[styles.avatarText,{color:avatarTheme.fg}]}>{initials}</Text></View><View style={styles.copy}><Text numberOfLines={1} style={styles.name}>{settings.displayName}</Text>{settings.professionalTitle?<Text style={styles.role}>{settings.professionalTitle}{settings.organization?` · ${settings.organization}`:''}</Text>:null}<View style={styles.metaRow}><Meta icon="email-outline" text={settings.email} styles={styles}/>{settings.barNumber?<Meta icon="card-account-details-outline" text={`Cédula ${settings.barNumber}`} styles={styles}/>:null}<View style={styles.planPill}><Icon name="crown-outline" size={12} color={colors.accent}/><Text style={styles.planText}>{plan}</Text></View></View></View><Pressable accessibilityRole="button" accessibilityHint="Abre o formulário de edição do perfil" onPress={()=>router.push('/profile/edit')} style={({pressed})=>[styles.editButton,pressed&&styles.pressed]}><Icon name="pencil-outline" size={16} color={colors.background}/><Text style={styles.editText}>Editar perfil</Text></Pressable></View>
<View style={styles.columns}><View style={styles.column}>
<Section icon="palette-outline" title="Aspeto" hint="Como a Lexora aparece neste dispositivo." styles={styles}><View style={styles.themeOptions}>{THEMES.map((item)=>{const on=preference===item.id;return <Pressable key={item.id} accessibilityRole="radio" accessibilityState={{checked:on}} onPress={()=>setPreference(item.id)} style={[styles.themeOption,on&&styles.themeOptionActive]}><Icon name={item.icon} size={22} color={on?colors.primary:colors.textMuted}/><Text style={[styles.themeText,on&&styles.themeTextActive]}>{item.label}</Text></Pressable>})}</View></Section>
<Section icon="bell-outline" title="Notificações" hint="Escolhe o que merece a tua atenção." styles={styles} flush>{toggle('checkbox-marked-circle-outline','Tarefas','Lembretes de tarefas atribuídas','taskNotifications')}<Divider styles={styles}/>{toggle('calendar-alert','Prazos','Avisos antecipados de datas importantes','deadlineNotifications')}<Divider styles={styles}/>{toggle('newspaper-variant-outline','Atualidade jurídica','Alterações legislativas e jurisprudência','legalUpdates')}</Section>
<Section icon="shield-lock-outline" title="Privacidade e segurança" styles={styles} flush>{toggle('incognito','Modo confidencial','Minimiza a retenção e exposição de dados','confidentialMode')}<Divider styles={styles}/>{toggle('fingerprint','Bloqueio biométrico','Preparado para Face ID ou impressão digital','biometricLock',(patch)=>{updateSettings(patch);Alert.alert('Bloqueio biométrico','A preferência ficou guardada. A validação nativa será ligada quando ativarmos a autenticação segura.');})}<Divider styles={styles}/>{toggle('chart-box-outline','Dados de utilização','Partilha opcional de métricas anónimas','analytics')}<Divider styles={styles}/><SettingRow symbol="file-document-outline" title="Política de privacidade" description="Retenção, tratamento e direitos" onPress={()=>Alert.alert('Privacidade por defeito','Os teus Casos e Clientes ficam guardados na tua conta, protegidos por autenticação. Não são utilizados para treino nem partilhados com terceiros.')}/></Section>
</View><View style={styles.column}>
<Section icon="credit-card-outline" title="Conta e plano" styles={styles} flush><SettingRow symbol="crown-outline" title={plan} description="Consultar preços e funcionalidades" onPress={()=>router.push('/billing')}/></Section>
<Section icon="database-outline" title="Os teus dados" hint="Guardados na tua conta Lexora e disponíveis nos teus dispositivos autenticados." styles={styles}><StatTiles items={[{icon:'account-group-outline',value:clients.length,label:'Clientes'},{icon:'briefcase-outline',value:cases.length,label:'Casos'},{icon:'checkbox-marked-circle-outline',value:tasks,label:'Tarefas'},{icon:'file-document-outline',value:documents,label:'Documentos'}]}/><Pressable accessibilityRole="button" onPress={()=>exportData().catch(()=>Alert.alert('Erro','Não foi possível exportar os dados.'))} style={({pressed})=>[styles.exportButton,pressed&&styles.pressed]}><Icon name="download-outline" size={18} color={colors.primary}/><Text style={styles.exportText}>Exportar os meus dados (JSON)</Text></Pressable></Section>
<Section icon="information-outline" title="Sobre" styles={styles} flush><SettingRow symbol="scale-balance" title="Aviso jurídico" description="A Lexora não substitui aconselhamento profissional" onPress={()=>Alert.alert('Aviso jurídico','A Lexora é uma ferramenta de informação e organização. Situações de risco ou complexidade elevada devem ser revistas por profissional habilitado.')}/><Divider styles={styles}/><SettingRow symbol="tag-outline" title="Versão" description="Lexora 0.2 · MVP local"/></Section>
<Pressable accessibilityRole="button" onPress={signOut} style={({pressed})=>[styles.logout,pressed&&styles.pressed]}><Icon name="logout" size={18} color={colors.danger}/><Text style={styles.logoutText}>Terminar sessão</Text></Pressable>
</View></View>
<Text style={styles.footer}>Lexora · Clareza jurídica digital</Text>
</ScrollView></SafeAreaView>}
function Section({icon,title,hint,flush,children,styles}:{icon:IconName;title:string;hint?:string;flush?:boolean;children:ReactNode;styles:ReturnType<typeof makeStyles>}){const {colors}=useAppTheme();return <View style={styles.section}><View style={styles.sectionHead}><View style={styles.sectionIcon}><Icon name={icon} size={17} color={colors.accent}/></View><View style={styles.copy}><Text style={styles.sectionTitle}>{title}</Text>{hint?<Text style={styles.sectionHint}>{hint}</Text>:null}</View></View><View style={flush?undefined:styles.sectionBody}>{children}</View></View>}
function Divider({styles}:{styles:ReturnType<typeof makeStyles>}){return <View style={styles.divider}/>}
function Meta({icon,text,styles}:{icon:IconName;text:string;styles:ReturnType<typeof makeStyles>}){const {colors}=useAppTheme();return <View style={styles.meta}><Icon name={icon} size={13} color={colors.textSoft}/><Text numberOfLines={1} style={styles.metaText}>{text}</Text></View>}
const makeStyles=(colors:ThemeColors)=>StyleSheet.create({screen:{flex:1,backgroundColor:colors.background},content:{width:'100%',maxWidth:1000,alignSelf:'center',paddingHorizontal:20,paddingBottom:45},pageIntro:{paddingTop:24,paddingBottom:18},eyebrow:{color:colors.accent,fontSize:10,fontWeight:'800',letterSpacing:1.4},pageTitle:{marginTop:5,color:colors.text,fontSize:28,fontWeight:'800'},pageSubtitle:{marginTop:5,color:colors.textMuted,fontSize:13},
profileCard:{flexDirection:'row',flexWrap:'wrap',alignItems:'center',gap:16,padding:20,borderWidth:1,borderColor:colors.border,borderLeftWidth:5,borderLeftColor:colors.primary,borderRadius:radius.xl,backgroundColor:colors.surface},avatar:{width:68,height:68,alignItems:'center',justifyContent:'center',borderRadius:radius.pill},avatarText:{fontSize:24,fontWeight:'900'},copy:{flex:1,minWidth:180},name:{color:colors.text,fontSize:20,fontWeight:'900'},role:{marginTop:3,color:colors.textStrong,fontSize:13,fontWeight:'600'},metaRow:{flexDirection:'row',flexWrap:'wrap',alignItems:'center',gap:12,marginTop:8},meta:{flexDirection:'row',alignItems:'center',gap:5,flexShrink:1},metaText:{color:colors.textMuted,fontSize:12},planPill:{flexDirection:'row',alignItems:'center',gap:4,paddingHorizontal:9,paddingVertical:4,borderRadius:radius.pill,backgroundColor:colors.surfaceMuted},planText:{color:colors.accent,fontSize:11,fontWeight:'800'},editButton:{minHeight:42,flexDirection:'row',alignItems:'center',gap:7,paddingHorizontal:15,borderRadius:radius.lg,backgroundColor:colors.primary},editText:{color:colors.background,fontSize:13,fontWeight:'800'},pressed:{opacity:.78},
columns:{flexDirection:'row',flexWrap:'wrap',gap:16,marginTop:16},column:{flex:1,minWidth:320,gap:16},
section:{borderWidth:1,borderColor:colors.border,borderRadius:radius.xl,backgroundColor:colors.surface,overflow:'hidden'},sectionHead:{flexDirection:'row',alignItems:'center',gap:12,paddingHorizontal:16,paddingVertical:13,borderBottomWidth:1,borderBottomColor:colors.border,backgroundColor:colors.surfaceMuted},sectionIcon:{width:30,height:30,alignItems:'center',justifyContent:'center',borderRadius:radius.sm,backgroundColor:colors.surface},sectionTitle:{color:colors.textStrong,fontSize:15,fontWeight:'800'},sectionHint:{marginTop:2,color:colors.textMuted,fontSize:12,lineHeight:17},sectionBody:{gap:14,padding:16},
themeOptions:{flexDirection:'row',gap:9},themeOption:{flex:1,alignItems:'center',gap:6,paddingVertical:14,borderWidth:1.5,borderColor:colors.border,borderRadius:radius.md,backgroundColor:colors.background},themeOptionActive:{borderColor:colors.primary,backgroundColor:colors.primaryLight},themeText:{color:colors.textMuted,fontSize:12,fontWeight:'700'},themeTextActive:{color:colors.primary,fontWeight:'900'},
divider:{height:1,marginLeft:64,backgroundColor:colors.border},exportButton:{minHeight:46,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:8,borderWidth:1,borderColor:colors.primary,borderRadius:radius.lg},exportText:{color:colors.primary,fontSize:13,fontWeight:'800'},
logout:{minHeight:50,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:8,borderWidth:1,borderColor:colors.danger,borderRadius:radius.lg},logoutText:{color:colors.danger,fontSize:14,fontWeight:'800'},footer:{marginTop:28,color:colors.textSoft,fontSize:11,textAlign:'center'}});
