export const LEGAL_AREAS = [
  'Direito Administrativo',
  'Direito Bancário e Financeiro',
  'Direito Civil',
  'Direito Comercial e Societário',
  'Direito da Concorrência',
  'Direito da Família e Menores',
  'Direito da Insolvência e Recuperação',
  'Direito da Propriedade Intelectual',
  'Direito da Saúde',
  'Direito das Contraordenações',
  'Direito das Sucessões',
  'Direito Digital, Tecnologia e Dados',
  'Direito do Ambiente',
  'Direito do Arrendamento',
  'Direito do Consumo',
  'Direito do Desporto',
  'Direito do Trabalho',
  'Direito Europeu',
  'Direito Fiscal e Tributário',
  'Direito Imobiliário e Urbanismo',
  'Direito Internacional Privado',
  'Direito Internacional Público',
  'Direito Marítimo',
  'Direito Penal',
  'Direito Processual Civil',
  'Direito Processual Penal',
  'Direito Público',
  'Direito dos Seguros',
  'Direito dos Transportes',
  'Proteção de Dados e Privacidade',
  'Registos e Notariado',
  'Outra',
] as const;

export type LegalArea = (typeof LEGAL_AREAS)[number];
