export const PROFESSIONAL_ROLES = [
  'Advogado',
  'Advogada',
  'Advogado Estagiário',
  'Advogada Estagiária',
  'Solicitador',
  'Solicitadora',
  'Agente de Execução',
  'Jurista',
  'Consultor Jurídico',
  'Consultora Jurídica',
  'Assistente Jurídico',
  'Assistente Jurídica',
  'Paralegal',
  'Estagiário de Direito',
  'Estagiária de Direito',
  'Notário',
  'Notária',
  'Conservador',
  'Conservadora',
  'Administrador de Insolvência',
  'Administradora de Insolvência',
  'Mediador',
  'Mediadora',
  'Árbitro',
  'Árbitra',
  'Outra',
] as const;

export type ProfessionalRole = (typeof PROFESSIONAL_ROLES)[number];
