import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useLocalSearchParams, useRouter } from 'expo-router'; import { SafeAreaView } from 'react-native-safe-area-context';
import { AppButton } from '@/components/app-button'; import { OfflineBanner } from '@/components/offline-banner'; import { ScreenHeader } from '@/components/screen-header'; import { StatusBadge } from '@/components/status-badge'; import { useCases } from '@/providers/cases-provider'; import { useClients } from '@/providers/clients-provider'; import { useAppTheme } from '@/providers/theme-provider'; import { radius, type ThemeColors } from '@/theme';
export default function ClientDetailScreen(){const {id}=useLocalSearchParams<{id:string}>();const router=useRouter();const {getClient,deleteClient}=useClients();const {cases}=useCases();const {colors}=useAppTheme();const styles=makeStyles(colors);const client=getClient(id);if(!client)return <SafeAreaView style={styles.screen}><ScreenHeader title="Cliente não encontrado" /></SafeAreaView>;const related=cases.filter((item)=>item.clientId===client.id||item.client===client.name);const remove=()=>Alert.alert('Eliminar cliente?','Os Casos existentes não serão eliminados.',[{text:'Cancelar',style:'cancel'},{text:'Eliminar',style:'destructive',onPress:()=>{deleteClient(id);router.replace('/clients');}}]);return <SafeAreaView style={styles.screen}><View style={styles.wrap}><ScreenHeader title={client.name} subtitle={`${client.type} · ${client.status}`} actionLabel="Editar" onActionPress={()=>router.push({pathname:'/clients/edit/[id]',params:{id}})} /><ScrollView contentContainerStyle={styles.content}>
<OfflineBanner />
<View style={styles.hero}><Text style={styles.eyebrow}>{client.type.toUpperCase()}</Text><Text style={styles.heroTitle}>{client.name}</Text><Text style={styles.heroText}>{client.email||'Email não indicado'} · {client.phone||'Telefone não indicado'}</Text></View>
<View style={styles.card}><Text style={styles.title}>Informação do cliente</Text><Detail label="NIF / NIPC" value={client.nif||'Não indicado'} styles={styles}/><Detail label="Email" value={client.email||'Não indicado'} styles={styles}/><Detail label="Telefone" value={client.phone||'Não indicado'} styles={styles}/><Detail label="Morada" value={client.address||'Não indicada'} styles={styles}/><Detail label="Notas" value={client.notes||'Sem notas'} styles={styles}/></View>
<View style={styles.card}><View style={styles.heading}><Text style={styles.title}>Casos associados</Text><Text style={styles.count}>{related.length}</Text></View>{related.length===0?<Text style={styles.muted}>Este cliente ainda não tem Casos.</Text>:related.map((item)=><Pressable key={item.id} onPress={()=>router.push({pathname:'/cases/[id]',params:{id:item.id}})} style={styles.caseRow}><View style={{flex:1}}><Text style={styles.caseRef}>{item.reference}</Text><Text style={styles.caseTitle}>{item.title}</Text><Text style={styles.muted}>{item.area}</Text></View><StatusBadge status={item.status}/></Pressable>)}<AppButton variant="ghost" onPress={()=>router.push({pathname:'/cases/new',params:{clientId:client.id,client:client.name}})}>Criar Caso para este cliente</AppButton></View>
<Pressable onPress={remove}><Text style={styles.delete}>Eliminar cliente</Text></Pressable></ScrollView></View></SafeAreaView>}
function Detail({label,value,styles}:{label:string;value:string;styles:ReturnType<typeof makeStyles>}){return <View style={styles.detail}><Text style={styles.detailLabel}>{label}</Text><Text style={styles.detailValue}>{value}</Text></View>}
const makeStyles=(colors:ThemeColors)=>StyleSheet.create({screen:{flex:1,backgroundColor:colors.background},wrap:{flex:1,width:'100%',maxWidth:900,alignSelf:'center',paddingHorizontal:20},content:{gap:16,paddingBottom:45},hero:{padding:22,borderRadius:radius.xxl,backgroundColor:colors.primary},eyebrow:{color:colors.accent,fontSize:9,fontWeight:'900',letterSpacing:1},heroTitle:{marginTop:14,color:colors.background,fontSize:25,fontWeight:'900'},heroText:{marginTop:7,color:colors.primarySoft,fontSize:12},card:{gap:12,padding:18,borderWidth:1,borderColor:colors.border,borderRadius:radius.xl,backgroundColor:colors.surface},title:{color:colors.textStrong,fontSize:18,fontWeight:'800'},heading:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},count:{color:colors.primary,fontSize:13,fontWeight:'900'},detail:{flexDirection:'row',justifyContent:'space-between',gap:18,paddingVertical:9,borderBottomWidth:1,borderBottomColor:colors.border},detailLabel:{color:colors.textMuted,fontSize:11},detailValue:{flex:1,color:colors.textStrong,fontSize:12,fontWeight:'600',textAlign:'right'},caseRow:{flexDirection:'row',alignItems:'center',gap:12,paddingVertical:12,borderBottomWidth:1,borderBottomColor:colors.border},caseRef:{color:colors.accent,fontSize:8,fontWeight:'900'},caseTitle:{marginVertical:3,color:colors.textStrong,fontSize:13,fontWeight:'800'},muted:{color:colors.textMuted,fontSize:10},delete:{padding:12,color:colors.danger,fontSize:12,fontWeight:'800',textAlign:'center'}});
