import { Fragment } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useAppTheme } from '@/providers/theme-provider';
import { radius, type ThemeColors } from '@/theme';
import { hashTheme } from '@/utils/palette';

export type PreviewItem = { symbol: string; eyebrow?: string; title: string; description: string; meta?: string; tone?: 'normal' | 'warning' | 'success' };
export type PreviewSection = { title: string; action?: string; items: PreviewItem[] };

export function ModulePreviewScreen({ eyebrow, title, subtitle, primaryAction, stats, sections }: { eyebrow: string; title: string; subtitle: string; primaryAction: string; stats?: { value: string; label: string }[]; sections: PreviewSection[] }) {
  const { colors } = useAppTheme(); const styles = makeStyles(colors);
  return <SafeAreaView edges={['top']} style={styles.screen}><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
    <View style={styles.intro}><View style={styles.introCopy}><Text style={styles.eyebrow}>{eyebrow}</Text><Text style={styles.title}>{title}</Text><Text style={styles.subtitle}>{subtitle}</Text></View><Pressable accessibilityRole="button" style={styles.primary}><Text style={styles.primaryText}>＋ {primaryAction}</Text></Pressable></View>
    {stats?.length ? <View style={styles.hero}>{stats.map((stat, index) => <Fragment key={stat.label}>{index > 0 ? <View style={styles.heroDivider} /> : null}<View style={styles.heroStat}><Text style={styles.heroValue}>{stat.value}</Text><Text style={styles.heroLabel}>{stat.label}</Text></View></Fragment>)}</View> : null}
    {sections.map((section) => <View key={section.title} style={styles.section}><View style={styles.sectionHeader}><Text style={styles.sectionTitle}>{section.title}</Text>{section.action ? <Text style={styles.link}>{section.action}</Text> : null}</View><View style={styles.list}>{section.items.map((item) => { const hash = hashTheme(colors, item.title); const symbolStyle = item.tone === 'warning' ? { backgroundColor: colors.warningBackground, color: colors.warningText } : item.tone === 'success' ? { backgroundColor: colors.successBackground, color: colors.successText } : { backgroundColor: hash.bg, color: hash.fg }; return <Pressable key={item.title} style={({ pressed }) => [styles.row, pressed && styles.pressed]}><View style={[styles.symbol, { backgroundColor: symbolStyle.backgroundColor }]}><Text style={[styles.symbolText, { color: symbolStyle.color }]}>{item.symbol}</Text></View><View style={styles.rowCopy}>{item.eyebrow ? <Text style={styles.rowEyebrow}>{item.eyebrow}</Text> : null}<Text style={styles.rowTitle}>{item.title}</Text><Text style={styles.rowDescription}>{item.description}</Text></View>{item.meta ? <Text style={styles.meta}>{item.meta}</Text> : null}<Text style={styles.chevron}>›</Text></Pressable>; })}</View></View>)}
    <View style={styles.previewNotice}><Text style={styles.previewTitle}>Pré-visualização do MVP</Text><Text style={styles.previewText}>Esta área representa a organização final. As ações serão ligadas ao backend nas próximas fases.</Text></View>
  </ScrollView></SafeAreaView>;
}

const makeStyles = (colors: ThemeColors) => StyleSheet.create({ screen:{flex:1,backgroundColor:colors.background},content:{width:'100%',maxWidth:1100,alignSelf:'center',paddingHorizontal:20,paddingBottom:42},intro:{flexDirection:'row',alignItems:'flex-end',justifyContent:'space-between',gap:18,paddingTop:24,paddingBottom:22},introCopy:{flex:1},eyebrow:{color:colors.accent,fontSize:10,fontWeight:'800',letterSpacing:1.2},title:{marginTop:5,color:colors.text,fontSize:30,fontWeight:'800'},subtitle:{maxWidth:650,marginTop:6,color:colors.textMuted,fontSize:13,lineHeight:19},primary:{minHeight:44,justifyContent:'center',paddingHorizontal:16,borderRadius:radius.md,backgroundColor:colors.primary},primaryText:{color:colors.background,fontSize:12,fontWeight:'800'},hero:{flexDirection:'row',alignItems:'center',padding:20,borderRadius:radius.xxl,backgroundColor:colors.primary},heroStat:{flex:1,alignItems:'center'},heroValue:{color:colors.background,fontSize:26,fontWeight:'900'},heroLabel:{marginTop:3,color:colors.primarySoft,fontSize:10,fontWeight:'700',textTransform:'uppercase',letterSpacing:.6},heroDivider:{width:1,height:34,backgroundColor:colors.primaryLight,opacity:.35},section:{marginTop:28},sectionHeader:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginBottom:11},sectionTitle:{color:colors.text,fontSize:18,fontWeight:'800'},link:{color:colors.primary,fontSize:12,fontWeight:'700'},list:{gap:10},row:{minHeight:82,flexDirection:'row',alignItems:'center',padding:14,borderWidth:1,borderColor:colors.border,borderRadius:radius.lg,backgroundColor:colors.surface},pressed:{opacity:.72},symbol:{width:42,height:42,alignItems:'center',justifyContent:'center',borderRadius:radius.md},symbolText:{fontSize:17,fontWeight:'800'},rowCopy:{flex:1,marginHorizontal:12},rowEyebrow:{color:colors.accent,fontSize:9,fontWeight:'800',letterSpacing:.7},rowTitle:{marginTop:2,color:colors.textStrong,fontSize:14,fontWeight:'700'},rowDescription:{marginTop:4,color:colors.textMuted,fontSize:11,lineHeight:16},meta:{maxWidth:110,color:colors.textSoft,fontSize:10,textAlign:'right'},chevron:{marginLeft:8,color:colors.textSoft,fontSize:22},previewNotice:{marginTop:28,padding:16,borderRadius:radius.lg,backgroundColor:colors.primaryLight},previewTitle:{color:colors.primary,fontSize:12,fontWeight:'800'},previewText:{marginTop:5,color:colors.textMuted,fontSize:11,lineHeight:17} });
