const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const assert = require('node:assert/strict');
const path = require('node:path');
const fs = require('node:fs/promises');
const output = path.resolve(__dirname, '../../../work/portal-check');

(async () => {
  await fs.mkdir(output, { recursive: true });
  const stamp = Date.now();
  const api = process.env.PORTAL_TEST_API_URL || 'http://127.0.0.1:8000';
  const web = process.env.PORTAL_TEST_WEB_URL || 'http://127.0.0.1:8765';
  const marker = await fetch(api + '/__portal_e2e__').then(response => response.json());
  assert.equal(marker.isolatedPortalTest, true, 'Start the isolated portal test server before running this test.');
  async function request(route, method, body, token) {
    const response = await fetch(api + route, { method, headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: `Bearer ${token}` } : {}) }, body: body ? JSON.stringify(body) : undefined });
    assert(response.ok, `${route}: ${response.status} ${await response.clone().text()}`);
    return response.status === 204 ? undefined : response.json();
  }
  const registered = await request('/auth/register', 'POST', { email: `portal-test-${stamp}@example.com`, password: 'PortalTest123!', displayName: 'Escritório de teste' });
  const owner = registered.accessToken;
  const clientId = `portal-client-${stamp}`, caseId = `portal-case-${stamp}`;
  const date = new Date().toISOString();
  await request('/clients', 'POST', { id: clientId, name: 'Cliente Portal Teste', email: `client-${stamp}@example.com`, type: 'Particular', status: 'Ativo', createdAt: date, updatedAt: date }, owner);
  await request('/cases', 'POST', { id: caseId, reference: 'PORTAL-TEST', title: 'Processo Portal Teste', client: 'Cliente Portal Teste', clientId, area: 'Direito Civil', court: '', responsible: 'Advogada de teste', priority: 'Normal', status: 'Em análise', createdAt: date, updatedAt: date, notes: [{ text: 'PRIVATE INTERNAL NOTE' }] }, owner);
  const browser = await chromium.launch({ channel: 'chrome', headless: true });
  const errors = [];
  try {
    const office = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
    await office.addInitScript(token => localStorage.setItem('@lexora/auth-token/v1', token), owner);
    const admin = await office.newPage();
    admin.on('pageerror', error => errors.push('office: ' + error.message));
    await admin.goto(web + '/client-portal');
    await admin.getByRole('button', { name: /^Cliente:/ }).click();
    await admin.getByRole('radio', { name: /Cliente Portal Teste/ }).click();
    await admin.getByRole('button', { name: 'Criar convite', exact: true }).click();
    await admin.getByRole('button', { name: 'Confirmar', exact: true }).click();
    const codeField = admin.getByRole('textbox', { name: 'Código de ativação — mostrado apenas agora' });
    await codeField.waitFor();
    const code = await codeField.inputValue();
    const url = await admin.getByRole('textbox', { name: 'Endereço do portal do cliente' }).inputValue();
    await admin.getByRole('textbox', { name: 'Atualização para o cliente' }).fill('Estamos a analisar a documentação entregue.');
    await admin.getByRole('button', { name: 'Publicar no portal', exact: true }).click();
    await admin.getByText('Informação publicada no portal.', { exact: true }).waitFor();
    await admin.getByRole('button', { name: 'Documentos', exact: true }).click();
    await admin.getByRole('textbox', { name: 'Documento necessário' }).fill('Contrato assinado');
    await admin.getByRole('button', { name: 'Criar pedido', exact: true }).click();
    await admin.getByText('Pedido guardado no portal.', { exact: true }).waitFor();
    const clientContext = await browser.newContext({ viewport: { width: 390, height: 844 }, acceptDownloads: true });
    const client = await clientContext.newPage();
    client.on('pageerror', error => errors.push('client: ' + error.message));
    await client.goto(url);
    await client.getByRole('button', { name: 'Ativar acesso', exact: true }).click();
    await client.getByRole('textbox', { name: 'Email indicado ao escritório' }).fill(`client-${stamp}@example.com`);
    await client.getByRole('textbox', { name: 'Código do convite' }).fill(code);
    await client.getByRole('textbox', { name: 'Definir palavra-passe (mínimo 10 caracteres)' }).fill('ClientPortal123!');
    await client.getByRole('button', { name: 'Ativar e entrar', exact: true }).click();
    await client.getByText('Estamos a analisar a documentação entregue.', { exact: true }).waitFor();
    assert(!(await client.locator('body').innerText()).includes('PRIVATE INTERNAL NOTE'));
    await client.getByRole('button', { name: 'Mensagens', exact: true }).click();
    await client.getByRole('textbox', { name: 'Mensagem', exact: true }).fill('Envio o contrato para revisão.');
    await client.getByRole('button', { name: 'Enviar mensagem no portal', exact: true }).click();
    await client.getByText('Mensagem guardada na conversa.', { exact: true }).waitFor();
    await client.getByRole('button', { name: 'Documentos', exact: true }).click();
    const chooserPromise = client.waitForEvent('filechooser');
    await client.getByRole('button', { name: 'Entregar documento', exact: true }).click();
    await (await chooserPromise).setFiles({ name: 'contrato.txt', mimeType: 'text/plain', buffer: Buffer.from('Documento de teste do portal.') });
    await client.getByText('Entregue · Disponível para revisão pelo escritório', { exact: true }).waitFor();
    const downloadPromise = client.waitForEvent('download');
    await client.getByRole('button', { name: 'Descarregar documento', exact: true }).click();
        const downloaded = await downloadPromise;
    assert.equal(downloaded.suggestedFilename(), 'contrato.txt');
    assert.equal(await fs.readFile(await downloaded.path(), 'utf8'), 'Documento de teste do portal.');
    assert(await client.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), 'Mobile horizontal overflow');
    await client.screenshot({ path: path.join(output, 'portal-client-mobile.png'), fullPage: true });
    await admin.getByRole('button', { name: 'Atualizar processo', exact: true }).click();
    await admin.getByRole('button', { name: 'Mensagens', exact: true }).click();
    await admin.getByText('Envio o contrato para revisão.', { exact: true }).waitFor();
    await admin.getByRole('button', { name: 'Pagamentos', exact: true }).click();
    await admin.getByRole('textbox', { name: 'Descrição', exact: true }).fill('Consulta inicial');
    await admin.getByRole('textbox', { name: 'Valor total a pagar (€), incluindo impostos aplicáveis' }).fill('123,45');
    await admin.getByRole('textbox', { name: 'Instruções de pagamento / referência' }).fill('Usar a referência indicada no documento de faturação.');
    await admin.getByRole('button', { name: 'Publicar valor', exact: true }).click();
    await admin.getByText('Valor publicado no portal.', { exact: true }).waitFor();
    await client.getByRole('button', { name: 'Atualizar processo', exact: true }).click();
    await client.getByRole('button', { name: 'Pagamentos', exact: true }).click();
    await client.getByText('Consulta inicial', { exact: true }).waitFor();
    assert.equal(await client.getByRole('button', { name: 'Confirmar recebimento', exact: true }).count(), 0);
    await admin.getByRole('button', { name: 'Confirmar recebimento', exact: true }).click();
    await admin.getByText('Estado do recebimento atualizado.', { exact: true }).waitFor();
    await client.getByRole('button', { name: 'Atualizar processo', exact: true }).click();
    await client.getByText(/123,45.*Recebido/).waitFor();
    await admin.screenshot({ path: path.join(output, 'portal-office-desktop.png'), fullPage: true });
    await client.getByRole('button', { name: 'Terminar sessão', exact: true }).click();
    await client.getByRole('button', { name: 'Entrar no portal', exact: true }).waitFor();
    await client.reload();
    await client.getByRole('textbox', { name: 'Email indicado ao escritório' }).fill(`client-${stamp}@example.com`);
    await client.getByRole('textbox', { name: 'Palavra-passe', exact: true }).fill('ClientPortal123!');
    await client.getByRole('button', { name: 'Entrar no portal', exact: true }).click();
    await client.getByRole('button', { name: 'Mensagens', exact: true }).click();
    await client.getByText('Envio o contrato para revisão.', { exact: true }).waitFor();
    await client.getByRole('button', { name: 'Documentos', exact: true }).click();
    await client.getByText('contrato.txt', { exact: true }).waitFor();
    await client.getByRole('button', { name: 'Pagamentos', exact: true }).click();
    await client.getByText(/123,45.*Recebido/).waitFor();
    assert.equal(await client.evaluate(() => localStorage.getItem('@lexora/auth-token/v1')), null);
    await admin.getByRole('button', { name: 'Revogar acesso', exact: true }).click();
    await admin.getByRole('button', { name: 'Confirmar', exact: true }).click();
    await admin.getByText('Acesso revogado.', { exact: true }).waitFor();
    await client.getByRole('button', { name: 'Atualizar portal', exact: true }).click();
    await client.getByRole('button', { name: 'Entrar no portal', exact: true }).waitFor();
    assert.equal(await client.getByText('Consulta inicial', { exact: true }).count(), 0);
    assert.deepEqual(errors, []);
    console.log('PASS: office invite/publication/request; client activation/message/upload/download; payment confirmation; logout/login persistence; isolated sessions; revocation; mobile layout; no browser runtime errors.');
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });


