"""baseline schema

Revision ID: 8ead4ba3d3c4
Revises: 
Create Date: 2026-09-20 01:59:35.073748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ead4ba3d3c4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('passwordHash', sa.String(length=255), nullable=False),
    sa.Column('displayName', sa.String(length=255), nullable=False),
    sa.Column('professionalTitle', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('plan', sa.String(length=20), nullable=False),
    sa.Column('createdAt', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('cases',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('ownerId', sa.String(length=36), nullable=False),
    sa.Column('reference', sa.String(length=60), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('client', sa.String(length=255), nullable=False),
    sa.Column('clientId', sa.String(length=64), nullable=True),
    sa.Column('area', sa.String(length=120), nullable=False),
    sa.Column('court', sa.String(length=255), nullable=False),
    sa.Column('processNumber', sa.String(length=120), nullable=False),
    sa.Column('responsible', sa.String(length=120), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('createdAt', sa.String(length=40), nullable=False),
    sa.Column('updatedAt', sa.String(length=40), nullable=False),
    sa.Column('notes', sa.JSON(), nullable=False),
    sa.Column('tasks', sa.JSON(), nullable=False),
    sa.Column('documents', sa.JSON(), nullable=False),
    sa.Column('timeline', sa.JSON(), nullable=False),
    sa.Column('entities', sa.JSON(), nullable=False),
    sa.Column('facts', sa.JSON(), nullable=False),
    sa.Column('legalIssues', sa.JSON(), nullable=False),
    sa.Column('missingFacts', sa.JSON(), nullable=False),
    sa.Column('collaboratorEmails', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['ownerId'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cases_ownerId'), 'cases', ['ownerId'], unique=False)
    op.create_table('clients',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('ownerId', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('nif', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=60), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('createdAt', sa.String(length=40), nullable=False),
    sa.Column('updatedAt', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['ownerId'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_ownerId'), 'clients', ['ownerId'], unique=False)
    op.create_table('portal_access',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('clientId', sa.String(length=64), nullable=False),
    sa.Column('ownerId', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('passwordHash', sa.String(length=255), nullable=False),
    sa.Column('inviteHash', sa.String(length=64), nullable=False),
    sa.Column('inviteExpiresAt', sa.String(length=40), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.String(length=36), nullable=False),
    sa.Column('failedAttempts', sa.Integer(), nullable=False),
    sa.Column('lockedUntil', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['clientId'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['ownerId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portal_access_clientId'), 'portal_access', ['clientId'], unique=True)
    op.create_index(op.f('ix_portal_access_ownerId'), 'portal_access', ['ownerId'], unique=False)
    op.create_table('portal_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('caseId', sa.String(length=64), nullable=False),
    sa.Column('clientId', sa.String(length=64), nullable=False),
    sa.Column('ownerId', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('author', sa.String(length=20), nullable=False),
    sa.Column('createdAt', sa.String(length=40), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['caseId'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portal_items_caseId'), 'portal_items', ['caseId'], unique=False)
    op.create_index(op.f('ix_portal_items_clientId'), 'portal_items', ['clientId'], unique=False)
    op.create_table('portal_publications',
    sa.Column('caseId', sa.String(length=64), nullable=False),
    sa.Column('clientId', sa.String(length=64), nullable=False),
    sa.Column('ownerId', sa.String(length=36), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('updatedAt', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['caseId'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('caseId')
    )
    op.create_index(op.f('ix_portal_publications_clientId'), 'portal_publications', ['clientId'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_portal_publications_clientId'), table_name='portal_publications')
    op.drop_table('portal_publications')
    op.drop_index(op.f('ix_portal_items_clientId'), table_name='portal_items')
    op.drop_index(op.f('ix_portal_items_caseId'), table_name='portal_items')
    op.drop_table('portal_items')
    op.drop_index(op.f('ix_portal_access_ownerId'), table_name='portal_access')
    op.drop_index(op.f('ix_portal_access_clientId'), table_name='portal_access')
    op.drop_table('portal_access')
    op.drop_index(op.f('ix_clients_ownerId'), table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_cases_ownerId'), table_name='cases')
    op.drop_table('cases')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
